Upgrade `black` which is broken with later versions of click
```
ImportError: cannot import name '_unicodefun' from 'click'
```

https://stackoverflow.com/a/71674345